version: "3.8"

services:
  cherry:
    image: cherry
    container_name: ${USER}_cherry
    user: docker
    working_dir: /cherry
    command: [ "python", "-m", "lib" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        BASE_IMAGE: $BASE_IMAGE
        TORCH_CUDA: $TORCH_CUDA
        PYTHON_VERSION: $PYTHON_VERSION
    environment: []
    volumes:
      - type: bind
        source: ./figures
        target: /cherry/figures
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ $DEVICE ]
              capabilities: [ gpu ]
        limits:
          memory: 64g
    cpuset: $CPUSET
    shm_size: 8g
    security_opt:
      - label:disable
