version: "3.8"

services:
  cherry-jupyter:
    image: cherry-jupyter
    container_name: $USER-cherry-jupyter
    user: docker
    working_dir: /home/docker
    command: [ "jupyter", "notebook", "--no-browser", "--ip", "0.0.0.0",
               "--port", "8000", "--notebook-dir", "/notebooks" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        CUDA_BASE: $CUDA_BASE
        CUDA_TORCH: $CUDA_TORCH
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: $HOME/notebooks
        target: /notebooks
      - type: bind
        source: $HOME/cherry/code
        target: /home/docker/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
        limits:
          cpus: '8'
          memory: 64g
    security_opt:
      - label:disable
    shm_size: 8g

  cherry:
    image: cherry
    container_name: $USER-cherry
    user: docker
    working_dir: /home/docker
    command: [ "python", "code/train.py" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        CUDA_BASE: $CUDA_BASE
        CUDA_TORCH: $CUDA_TORCH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
        limits:
          cpus: '8'
          memory: 64g
    security_opt:
      - label:disable
    shm_size: 8g
