version: "3.8"

services:
  cherry:
    image: cherry
    container_name: ${USER}_cherry
    user: docker
    working_dir: /home/docker
    command: [ "jupyter", "notebook", "--no-browser", "--ip", "0.0.0.0",
               "--port", "8000", "--notebook-dir", "/notebooks" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: $HOME/notebooks
        target: /notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
        limits:
          cpus: '8'
          memory: 64g
    security_opt:
      - label:disable
