version: "3.8"

services:
  cherry_jupyter:
    image: cherry_jupyter
    container_name: $USER-cherry_jupyter
    user: docker
    working_dir: /home/docker
    command: [ "jupyter", "notebook", "--no-browser", "--ip", "0.0.0.0",
               "--port", "8000", "--notebook-dir", "/notebooks" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: $HOME/notebooks
        target: /notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '2' ]
              capabilities: [ gpu ]
        limits:
          cpus: '8'
          memory: 64g
    security_opt:
      - label:disable

  cherry_experiment:
    image: cherry_experiment
    container_name: $USER-cherry_experiment
    user: docker
    working_dir: /home/docker
    command: [ "python", "code/train.py" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '2' ]
              capabilities: [ gpu ]
        limits:
          cpus: '8'
          memory: 64g
    security_opt:
      - label:disable
