version: "3.8"

services:
  cherry:
    image: cherry
    container_name: grigoryev_cherry
    command: ["jupyter", "notebook", "--no-browser", "--ip", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    network_mode: "host"
    working_dir: /app
#    volumes:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
        limits:
          cpus: '1'
          memory: 1g
    security_opt:
      - label:disable
