#!/bin/bash

PORT=8000

docker compose build -q cherry
docker compose run --rm \
  --name ${USER}-cherry-jupyter \
  -p ${PORT}:80 \
  -v ./lib:/cherry/icelib \
  -d cherry \
  jupyter notebook --no-browser --ip 0.0.0.0 --port 80
sleep 1
docker exec ${USER}-cherry-jupyter jupyter notebook list
